[general]
import = ["~/.config/alacritty/themes/nordic.toml"]

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 0, y = 0 }
decorations = "Full"
opacity = 1.0
blur = true


[font]
normal = { family="ZedMono Nerd Font", style='Light'}
size = 19.5
offset = { x = -1, y = -5}

[bell]
animation = "EaseOutCubic"
duration = 10


[cursor]
style = {shape="Block", blinking="off"}
