[colors.primary]
background = "0x000000"  # Чистый чёрный
foreground = "0xFFFFFF"  # Белый текст

[colors.cursor]
text = "0x000000"
cursor = "0xFFFFFF"

[colors.normal]
black = "0x000000"
red = "0xFF0000"
green = "0x00FF00"
yellow = "0xFFFF00"
blue = "0x0000FF"
magenta = "0xFF00FF"
cyan = "0x00FFFF"
white = "0xFFFFFF"

[colors.bright]
black = "0x555555"
red = "0xFF5555"
green = "0x55FF55"
yellow = "0xFFFF55"
blue = "0x5555FF"
magenta = "0xFF55FF"
cyan = "0x55FFFF"
white = "0xFFFFFF"
